- name: Generate the host SSH configuration file new node
  template: src=add_node_config.j2 dest=roles/ssh_auth/files/add_node_config mode=0644

- name: Generate the SSH script new node
  template: src=add_ndoe_ssh_auth.sh.j2 dest=roles/ssh_auth/files/add_ndoe_ssh_auth.sh mode=0755

- name: Execute the SSH script new node
  shell: cd roles/ssh_auth/files && /bin/bash add_ndoe_ssh_auth.sh